### PR TITLE
Added Lightworks icon

### PR DESCRIPTION
**Pull request by yioannides**
Added an icon for the video editor, [Lightworks](https://lwks.com/).

This icon is based on the rebranded LWKS logo and the website's fav icon, otherwise, the desktop icon is still using their old branded logo, which does not look very appealing:
image

Also, there seems to be a flatpak version available, but it's reserved for premium users, so I skipped creating symlinks. Once again, my apologies for the red lines in the meson.build files, not sure why that occurs.

### CODE REVIEW

**Comment by yioannides** [comment]
Alright, I will redesign it and base it on the original icon then.

**Comment by yioannides** [comment]
How's this?

lightworks

**Comment by somepaulo** [comment]
Thank you! Check the Papirus icon and maybe adapt that. Remove the shadow lines and add the thickness and glow.

**Comment by somepaulo** [comment]
> How's this?

Just saw this. Nice. I'll come back to it later today.

**Comment by somepaulo** [comment]
I just realised you didn't merge the new version and merged this. I grabbed the one from your comment and modified it a bit. Have a look. Not sure if I should leave the shark and film thickness or make it flat like your version.

**Comment by yioannides** [comment]
The color density and contrast is somewhat aesthetically unpleasant, but it does adhere to both upstream and GNOME, though it would be best to use [GNOME's reds](https://developer.gnome.org/hig/reference/palette.html) on this one.

**Pull request merged**
