### PR TITLE
Added scalable, symbolic for OnlyOffice

### PR DESCRIPTION
**Pull request by ArberTu474**
This should resolve [#70](https://github.com/somepaulo/MoreWaita/issues/70)

### CODE REVIEW

**Comment by dusansimic** [comment]
Hi @ArberTu474. Thanks for the contribution. The icon looks great!

Could you just make the scalable (colored) icon 128x128px (most of other icons are that size), and the symbolic (black and white) icon 16x16px?

Also could you crop the icons so there is no padding on top and bottom of the icon? You could see that there is no padding on icons for LibreOffice Writer for example ([scalable](https://github.com/somepaulo/MoreWaita/blob/main/apps/scalable/libreoffice-writer.svg), [symbolic](https://github.com/somepaulo/MoreWaita/blob/main/apps/symbolic/libreoffice-writer-symbolic.svg)).

**Comment by ArberTu474** [comment]
Thanks for replying. I will work on that.

**Comment by ArberTu474** [comment]
I took a look to the icons and saw that the colored one was 128px and te small one was 16px , but I removed the padding.

**Comment by dusansimic** [comment]
Interesting. For some reason they are displayed in GitHub as a different size.

Thanks for the contribution!

**Pull request merged**
