### PR TITLE
README.md refresh + new icons (Logseq, Retroarch, Zed)

### PR DESCRIPTION
**Pull request by yioannides**
I took the liberty of giving MoreWaita's README.md a bit of a refresh, to actually showcase the icons themselves and improve legibility, because the paragraphs of iterative information might be a bit too much and currently feels like a data research report, in my opinion.

I also optimized the installation & troubleshooting scripts and changed the About to: "An expanded Adwaita-styled icon theme for GNOME", to match the showcase screenshot.

Lastly, I added icons for the apps below, but please feel free to check whether everything is okay:

**Logseq** : #156 
**Retroarch**: #126 
**Zed**: #159 

Hope you like it!

### CODE REVIEW

**Comment by yioannides** [comment]
Also added icons for Logseq and Zed, should close #156 and #159

**Comment by somepaulo** [comment]
Thank for the effort. I'm going to incorporate some of the changes into the readme, and I'm going to use the icons, but I'm not merging this since not all is going in.

On a separate note, all icons have to exist only once as an actual `.svg` file. All name variants for the same icon should be symlinks to that `.svg` file. And those symlinks should be created from within the same directory as that `.svg` file without using any paths (because they get hardcoded), like so: `ln -s original.svg alternative.svg`. Also, all app icons should have their respective symbolic icon with the same name and `-symbolic` in it, and with the same one file and symlinks approach. I'll write a document for contributors to make those things clear from the start.

**Comment by somepaulo** [comment]
Added [CONTRIBUTING.md](https://github.com/somepaulo/MoreWaita/blob/main/CONTRIBUTING.md)

**Comment by yioannides** [comment]
It's weird, because I always create the symlinks in Nautilus via `Ctrl + Shift + M`, but they seem to become unlinked by the time they're uploaded on Github:

image

Also, I tried making a new merge request for every new development, but I have no idea how to do so. These are the only options I have:

image
image

Anyway, I will figure out eventually, so feel free to close this merge request whenever you are done transferring the thing you want to use in the master branch.

**Comment by somepaulo** [comment]
Thank you!
I added all the icons you proposed (modified) and some of the suggested changes in README.md
Closing this PR.

**Pull request closed without merging**
