### PR TITLE
Fixes retroarch.svg

### PR DESCRIPTION
**Pull request by yioannides**
Referring to #171 

Aligned icon to center to match with every other horizontally designed MoreWaita icon

### CODE REVIEW

**Comment by somepaulo** [comment]
This is not a bug.

All Adwaita icons align to a baseline, not to the centre. Circular icons have a lower baseline than non-circular ones. Check https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/master/src/template.svg and have a look at icons like mockoon, nufraw, opensnitch, spek...

**Comment by yioannides** [comment]
Noted, thank you!

**Comment by somepaulo** [comment]
I do agree that Retroarch and Mockoon look off. I'll think of a different baseline. Maybe still off centre, but maybe align to the top edge of a taller icon, like the ruler one. You're not the first person noticing this, so there's definitely a perception issue.

**Comment by yioannides** [comment]
Yeah, I agree. I think halfway between the current baseline and the definitive center could be perfect, to give you that sense of evenness and perceptual balance between icons, but then it begs the question if is it okay for MoreWaita to take such initiatives. I'm obviously all for it, but it's your vision in the end of the day!

**Pull request closed without merging**
