### PR TITLE
Added Webcord, office apps, and some scientific computing apps

### PR DESCRIPTION
**Pull request by GabePoel**
Added icon for Webcord based on the existing Discord and Discord Canary icons. Also added Mathematica, Octave, Okular, and a bunch of Microsoft Office/Google Suite apps. Note that I haven't added symbolic versions of all the app icons. I also put in mimetypes for everything.

### CODE REVIEW

**Comment by somepaulo** [comment]
Thanks for this huge commit.

I can't accept all of the proposed icons.  
Office file mimes (documents, spreadsheets, presentations, html files) are already being taken care of by Adwaita, which we don't interfere with, and there's no point differentiating their icons for one particular office suite. If these particular mimes you've included don't get covered by Adwaita for some reason, what we can do is include Adwaita's original icons for them and create symlinks to them with the needed filenames.

So if you don't mind, I'll cherry pick from this commit.

**Comment by iaacornus** [comment]
hi can you make a merge request of this in the revived repo [MoreWaita-Dev/MoreWaita](https://github.com/MoreWaita-Dev/MoreWaita)? Thank you!

**Comment by iaacornus** [comment]
hi, i'll be absorbing this in my repo. Thank you for this nice contribution @GabePoel

**Comment by somepaulo** [comment]
Finally closing this since I've implemented everything I wanted from this PR, albeit differently. Only left out Google and Microsoft stuff that doesn't have Linux apps. Everything else in this huge PR is now in the theme.

**Pull request closed without merging**
