### PR TITLE
Add meson build system

### PR DESCRIPTION
**Pull request by dusansimic**
This patch adds meson build system so it can be used for installing the icon theme and having a standardized process of doing so. It makes it easier for package maintainers to maintain distribution packages.

It also contains utility scripts `dump_regulars.sh` and `dump_groups.sh` that made it easier to write the meson build specs. They could be extended to serve multiple purposes (@somepaulo mentioned making lists for html files to make screenshots, these utilities could be extended to work as generators for those html files).

- [x] Utility scripts
- [x] meson build spec
- [x] Documentation

Closes: #37

### CODE REVIEW

**Comment by somepaulo** [comment]
Should I go and merge this before pushing new changes and releasing v.44, or do you want to tick off the Documentation checkmark first?

**Comment by dusansimic** [comment]
I haven't yet been able to test it with and actual package so I'd hold off until I do that. You can push v44 and we'll probably merge this for v44.1.

**Comment by somepaulo** [comment]
Great! Thank you!

I've read through the docs. Everything seems fine.

As a total noob with Meson, I don't quite get the process for adding new icons and symlinks to the theme.  
I've looked at the code involved, and I understand what's being done, but still a bit confused.

Say I create a new icon in an existing folder (don't see new folders being added any time soon). Then I create all the symlinks to that icon (I take care not to chain links, so all symlinks link to actual files).  
Then, what do I do to update Meson build definitions? Just do a `./dump_regulars.sh && python dump_groups.py` from wherever those scripts are? Or should I point them to the particular folder where the changes were made?  
And what happens with merged pull requests? Should I execute the scripts after merging new icons?

Sorry for this flood of questions. I just want to make sure I understand exactly what to do after switching to meson.

**Comment by dusansimic** [comment]
> Sorry for this flood of questions. I just want to make sure I understand exactly what to do after switching to meson.

No problem at all, all of the questions are completely valid! Sorry for just pushing this without a somewhat readable docs or help page for running the commands 😅. I'll push those docs and probably add the help parameter for scripts (could be useful when running them instead of looking through the docs) in the following days and also answer all the questions.

**Comment by dusansimic** [comment]
> Then I create all the symlinks to that icon (I take care not to chain links, so all symlinks link to actual files).

This shouldn't be an issue even if it happens. It's [made sure in the python script](https://github.com/somepaulo/MoreWaita/pull/44/files#diff-5bbc35d064cfceb790e791012d3b2dab35e24f107f49d400b9704eb106e8a3caR28-R30) that even chain links are included and created.

> Then, what do I do to update Meson build definitions? Just do a ./dump_regulars.sh && python dump_groups.py from wherever those scripts are? Or should I point them to the particular folder where the changes were made?

`dump_regulars.sh` and `dump_groups.py` will just print the list of files that need to be in the Meson build spec (there is no automated population of build spec yet but that could be a future improvement of these scripts). This needs to be done only when files in those directories have their names changed (including links being relinked) and when files get added or removed.

> Or should I point them to the particular folder where the changes were made?

To use them, you'll need to run something along the lines of this:
```sh
$ ./dump_regulars.sh apps/scalable/ # mind the trainling slash, it's required
$ ./dump_groups.sh apps/scalable # trailing slash is not required here
```

This is also documented now in the packaging doc. By default they use the current directory which could be useful if you install those scripts globally so you just `cd` into the directory you want but imho, it's better to just type the directory name.

> And what happens with merged pull requests? Should I execute the scripts after merging new icons?

As before, they need to be executed only when filenames and links are changed, new icons are added or some icons are removed. There is no need to execute them when icons (files) are only modified since Meson deals with filenames and if they already exist, it doesn't affect anything.

A good improvement would be to automate this as much as possible so we could offload all this work to GitHub pipelines or something like that. I'll research this option. Keep in mind that we have all this work to do because Meson for now copies files instead of maintaining symlinks. If this were implemented in Meson, it would eliminate the need for additional scripts.

If you'd prefer it we could hold off on this pr so I could implement a more automated system for automatically adding all the lists to Meson build specifications.

**Comment by somepaulo** [comment]
I'm OK with pushing this.  
I've just published v44.1 with some earlier changes to the file structure. I've simply removed unused folders, merged `status` into `panel` and moved all icons there into the `symbolic` subfolder instead of `scalable`. Can you check that this doesn't break your changes?
  
It would be great to have some sort of automation for populating the `.build` files, but I'm willing to do this manually for now (and learn something about Meson in the process). Do I understand correctly that each folder should have its own `.build` file, including the theme's root folder?

Also, while looking up info on Meson and symlinks, I came across this bit of workaround code. No idea if it's of any help, but here goes:
```meson
name = 'new'
custom_target(
  name,
  output : name,
  input : old,
  command : ['ln', '-s', '@INPUT', '@OUTPUT'],
  install : true,
  install_dir : get_option('bindir')
)
```

And [this](https://github.com/learnbyexample/learn_gnused/blob/master/gnu_sed.md#adding-content-from-file) might help with automation for replacing lines in `.build` files.

**Comment by somepaulo** [comment]
I'll go ahead and merge this to see how it goes and learn something.

**Comment by somepaulo** [comment]
OK. I've merged it.  
I then updated the `.build` files to match the new folder structure, updated the scripts to include all the padding needed, ran them, and updated all the `.build` files with all the current filenames.

There are two things I'm not very comfortable with.  
I don't like the scripts sitting in the theme's root. I'll put them into a `dev` subfolder.
And the second thing I don't like is all the extra files getting installed along with the actual theme:

Screenshot from 2023-05-19 22-01-03

I think that the .github folder, all the dot files, scripts, build files, and text files (apart from license) should be removed from the final installation folder. Can this be achieved with Meson? Do AUR .PKGBUILDS have to change to take advantage of meson? Can we have a script that would do a tidy install in case of manual installation? 

I'm now trying to implement bash automation to pipe the scripts' output straight into the relevant `.build` files based on the working directory.  Playing around. Might come up with something useful.

**Comment by somepaulo** [comment]
> I'll put them into a `dev` subfolder.

I put them in `_dev` and updated PACKAGING.md to reflect the new location in the example.

> Can we have a script that would do a tidy install in case of manual installation?

I created manual install scripts that copy only the theme without any extras to either `/usr/share/icons/` or `~/.local/share/icons`, and update the README to change manual install instructions.

**Comment by somepaulo** [comment]
You should probably change the `.PKGBUILD` in AUR to use `rsync` instead of `cp` like so:

```shell
rsync -av --exclude='*.build' --exclude='*.sh' --exclude='*.py' --exclude='*.md' --exclude=.git --exclude=.github --exclude=.gitignore --exclude=dev "$(pwd -P)" "$pkgdir/usr/share/icons"
```

**Comment by dusansimic** [comment]
> Do I understand correctly that each folder should have its own .build file, including the theme's root folder?

Yes, the root one is "called" first and then it "calls" each of the nested ones.

> Also, while looking up info on Meson and symlinks, I came across this bit of workaround code. No idea if it's of any help, but here goes:

That is essentially what people used before `install_symlink` function was introduced in meson. The thing that would be useful now is that meson maintains the links even when whole directories are installed recursively, not just resolving the links and making duplicate files.

> I don't like the scripts sitting in the theme's root. I'll put them into a dev subfolder.

No problem, all fine by me :)

> Can this be achieved with Meson?

Yes, meson installs only what's specified in the meson build files. You can try it out by running the meson installation process manually

```sh
# creates all the build scripts in the build directory while setting the source directory to the current one
$ meson setup build .
# install all files to a specified destination directory
$ meson install -C build --destdir $PWD/dest
```

This would install the theme into the dest directory relative to from where the command is run. You can then list out all the files that are installed. and see what's the contents of the MoreWaita directory after installation.

```
total 32
drwxr-xr-x 7 dusan dusan 4096 22. maj. у 01:25  ./
drwxr-xr-x 3 dusan dusan 4096 22. maj. у 01:25  ../
drwxr-xr-x 4 dusan dusan 4096 22. maj. у 01:25  apps/
lrwxrwxrwx 1 dusan dusan    4 22. maj. у 01:25 'apps@2x' -> apps/
-rw-r--r-- 1 dusan dusan 2627 10. mar. у 09:52  index.theme
drwxr-xr-x 3 dusan dusan 4096 22. maj. у 01:25  mimes/
lrwxrwxrwx 1 dusan dusan    5 22. maj. у 01:25 'mimes@2x' -> mimes/
drwxr-xr-x 3 dusan dusan 4096 22. maj. у 01:25  panel/
lrwxrwxrwx 1 dusan dusan    5 22. maj. у 01:25 'panel@2x' -> panel/
drwxr-xr-x 4 dusan dusan 4096 22. maj. у 01:25  places/
lrwxrwxrwx 1 dusan dusan    6 22. maj. у 01:25 'places@2x' -> places/
drwxr-xr-x 3 dusan dusan 4096 22. maj. у 01:25  status/
lrwxrwxrwx 1 dusan dusan    6 22. maj. у 01:25 'status@2x' -> status/
```

> Do AUR .PKGBUILDS have to change to take advantage of meson?

Yes. They can take the advantage of this new build system only once it's incorporated into a release, which would be the next one.

> Can we have a script that would do a tidy install in case of manual installation?

Yes. I'll fix them.

> I'm now trying to implement bash automation to pipe the scripts' output straight into the relevant .build files based on the working directory. Playing around. Might come up with something useful.

Great! But I should mention, in my experience sometimes bash (and grep/sed) can be a bit difficult to work with on more complex problems. I was thinking about using Python `re` package for regular expressions and match the segment that needs to be changed with a multi-line expression. I'll see if I can have something to test out tomorrow. If it works well, we could then move on to automating it with GitHub Actions.

> You should probably change the .PKGBUILD in AUR to use rsync instead of cp like so:

On Arch, `rsync` is not installed by default which would mean that it would need to be a dependency. It does require more work but I think it would be better to use just `cp`. Each file and directory could be copied recursively one by one. I'll fix that now.

**Comment by somepaulo** [comment]
Thank you for all the answers!

> On Arch, `rsync` is not installed by default

Oops. Didn't know that. It is on my system, pulled by `reflector`.
I've updated the manual install scripts to use `cp` instead.
I think they can be used to update as well, if I got all the options right. At least I get no errors.

> in my experience sometimes bash (and grep/sed) can be a bit difficult

What caught my attention is that `sed` can apparently delete all content between specified strings and replace it with our output. Since each list uses different names and different brackets, that seemed quite easy to accomplish. I haven't had time to look into it yet though.

**Comment by dusansimic** [comment]
> What caught my attention is that sed can apparently delete all content between specified strings and replace it with our output.

That's correct, and I've used it for a few scripts but personally found it more comfortable and readable to work with python instead. Since links script is already written in python, I took the liberty and wrote the regular files function in that same script. I've opened the pr for testing so you can check out if it works fine for you. All build files contain comment that mark the begging and end of a segment so we wouldn't need to play the guessing game with brackets 😄.

**Pull request merged**
