### PR TITLE
Added Endless Sky icon

### LINKED ISSUE #224: Icon request: Endless Sky
### Name of app

Endless Sky

### Link to official icon

https://upload.wikimedia.org/wikipedia/commons/0/05/Endless_Sky_icon.png

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

io.github.endless_sky.endless_sky

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yioannides**
Closes #224 

Since diagonal icons don't follow GNOME HIG, I went for a squished beveled icon in the style of the only vehicle-based GNOME icon I could find, [Railway](https://apps.gnome.org/DieBahn/). I think it looks pretty nice, but feel free to edit it. I think a top view one could be also nice, but the perspective view might be a bit trippy. As for the symbolic icon, I made an icon somewhat similar to the original.

My apologies again for the meson.build files, I don't know what I'm doing wrong. I think I'll do the next ones by hand, in order not to waste your time.

(also please check #219 for some additional comments I made)

### CODE REVIEW

**Comment by somepaulo** [comment]
That's actually a good start. There's not much of the original we can actually keep here. It's way off Adwaita styling.
Have a look at the [GPSd](./../blob/main/scalable/apps/gpsd-logo.svg) icon.  
That's an acceptable angle, and I think it could be the same for Endless Sky.

**Comment by somepaulo** [comment]
The easiest way about this would be to take the [Papirus icon](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/64x64/apps/endless-sky.svg), remove its background, glows and shadows, and add Adwaita depth and corner shine to the actual spaceship. Pretty much what I did with GPSd along with using the original colours instead of Papirus ones.

endless-sky

**Comment by yioannides** [comment]
I initially tried doing a diagonal one which was going well, until I had to deal with the perspective which totally broke my brain and wasn't sure what I was looking at. The GPSd icon looks great though, it makes for a good reference. It will be easier to base the similar symbolic icon on the original as well.

I will be able to revisit it tomorrow, but if you get around to it first, no problem.

**Comment by yioannides** [comment]
This is as far as I've gone, but I'm really drawing blanks as to how to approach the perspective, even after referencing the GPSd icon side by side:

endless-sky-test

**Comment by somepaulo** [comment]
Looks nice. For the thickness, I usually duplicate any shapes that would be showing, move them straight down two arrow key strokes (exactly 4 px), send them to the bottom layer (so they're mostly covered by the original shapes, then either only reduce colour lightness by 20 points or do a gradient for shining corners (still making the main colour darker), and finally compensate for any corners sticking out by adding nodes to the shape and moving them.

**Comment by yioannides** [comment]
With or without body shadow?

With:
endless-sky-bodyshadow

Without:
endless-sky-nobodyshadow

**Comment by somepaulo** [comment]
Merging and applying changes. You can then check all the different parts and layers where I changed the nodes of several thickness parts to create a cohesive perspective.

**Comment by yioannides** [comment]
Ah, I see now, that's a great edit, thank you.

**Pull request merged**
