### PR TITLE
Added FreeCAD Icon

### LINKED ISSUE #176: Icon request: FreeCAD
### Name of app

FreeCAD

### Link to official icon

https://fpa.freecad.org/handbook/process/logo.html

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

org.freecad.FreeCAD

### Optional image of the app icon

FreeCAD

### Additional context

I don't know if the original logo is flat enough to comply with the Adwaita style or it would require changes.

### PR DESCRIPTION
**Pull request by Nokse22**
Closes #176

### CODE REVIEW

**Comment by hasecilu** [comment]
I think icon looks good, I think symbolic icon is missing

**Comment by somepaulo** [comment]
Thank you for your contribution.  
You need a 16x16 symbolic icon with the same name and `-symbolic` added to it in the respective `symbolic/apps` folder. You also need symlinks with other names the icon may have on different systems. Check [CONTRIBUTING.md](./../blob/main/CONTRIBUTING.md) for details.

**Comment by somepaulo** [comment]
I'm merging this and adding the missing symbolic icon and symlinks myself.

**Comment by Nokse22** [comment]
Thank you for taking this on. I apologize for the delay in completing it myself. I planned to get to it.

**Pull request merged**
